<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageVersion Include="bunit" Version="2.9.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="3.1.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Azure.Cosmos" Version="3.62.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.51.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.47" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Graph" Version="6.2.0" />
    <PackageVersion Include="Microsoft.Graph.Beta" Version="6.2.0-preview" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageVersion Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
    <PackageVersion Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />
    <PackageVersion Include="Microsoft.NET.Sdk.Razor" Version="3.1.32" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.QualityTools.Testing.Fakes" Version="18.1.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.Security.Permissions" Version="10.0.3" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

</Project>
